services:
  pgdatabase:
    image: postgres:13
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=ny_taxi
    volumes:
      - "postgres_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    

  # no need to define --network tag in docker compose..it will auto create a network for both image since they are under the same service 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/C/Users/hp/data_engineering_bootcamp/week1_basics/docker/pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
volumes:
  postgres_volume:



