services:
  pgdatabase:
    image: postgres:13
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=ny_taxi
    volumes:
      - "postgres_volume:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow

    

  # no need to define --network tag in docker compose..it will auto create a network for both image since they are under the same service 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_volume:/var/lib/pgadmin"
    ports:
      - "8090:80"
    networks:
      - airflow
volumes:
  postgres_volume:
  pgadmin_volume:


networks:
  airflow:
    external:
      name: airflow_default



